site_name: A context-aware genomic language model for gene spatial expression imputation, pattern detection, and function discovery 
theme:
  name: null
  custom_dir: 'cinder'
extra_css:
  - "css/mystyle.css"
nav:
  - SIGEL: index.md